### ISSUE TITLE
Cannot clone Git repository

### ISSUE THREAD

**Issue by camnguyen92** [UITrainingTeam/basic-web#2]
Can not git clone repository when create command : git clone https://github.com/UITrainingTeam/basic-web.git
Message error : "Cloning into 'basic-web'...
remote: Repository not found.
fatal: repository 'https://github.com/UITrainingTeam/basic-web.git/' not found"

**Comment by longlv91** [comment]
@camnguyen92  I have changed this repo to public. Please try again.

**Comment by camnguyen92** [comment]
Got an issue when push change on new branch "working"
Command : Ans-MacBook-Pro:basic-web annguyenngoc$ git push --set-upstream origin working
Password for 'https://camnguyen92@github.com': 
Error message :remote: Permission to UITrainingTeam/basic-web.git denied to camnguyen92.
fatal: unable to access 'https://camnguyen92@github.com/UITrainingTeam/basic-web.git/': The requested URL returned error: 403

**Comment by longlv91** [comment]
I changed your role to Owner. So I think you can do everything with this repository.
